# Workflow name
name: GitHub-Profile-Summary-Cards

on:
  schedule:
    # Trigger every 24 hours
    - cron: "0 0 * * *"  # This triggers at midnight UTC every day
  # Enable manual trigger
  workflow_dispatch:

jobs:
  # Job id
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      # Step 1: Checkout the current repository
      - uses: actions/checkout@v2
      
      # Step 2: Use the action from vn7n24fzkq/github-profile-summary-cards repository, release branch
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
