# GitHub Action's name
name: Progress Bar CI

# Define the events that trigger the GitHub Action
on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "0 */6 * * *" # Automatically triggers every 6 hours

# Define jobs in the workflow
jobs:
  build: # Job name
    runs-on: ubuntu-latest # Running environment

    # Define the job steps
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history to ensure proper git operations

      - name: Use Node.js # Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14.x" # Use Node.js version 14.x

      - name: Update README.md # Update README.md file
        run: node index.js > README.md # Execute index.js and redirect output to README.md

      - name: Commit changes & Push # Commit changes and push
        run: |
          git config --global user.name 'github-actions[bot]' # Configure GitHub username
          git config --global user.email 'github-actions[bot]@users.noreply.github.com' # Configure GitHub user email
          git add README.md # Add the updated README.md to the commit
          git commit -m "bot: update README.md automatically" # Commit the changes
          git push origin HEAD # Push to the current branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GitHub token for authentication
